# Generated by Django 4.0.2 on 2022-02-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due date'),
        ),
    ]
